-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 19:18:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET utf8 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NULL,
  `nombre` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `password` TEXT NULL,
  `fecha` TIMESTAMP NULL,
  `foto` TEXT NULL,
  `pais` TEXT NULL,
  `codigo_pais` TEXT NULL,
  `ciudad` TEXT NULL,
  `direccion` TEXT NULL,
  `telefono_movil` TEXT NULL,
  `verificacion` INT NULL,
  `email_encriptado` TEXT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

INSERT INTO `usuarios` (`id_usuario`, `perfil`, `nombre`, `email`, `password`, `fecha`, `foto`, `pais`, `codigo_pais`, `ciudad`, `direccion`, `telefono_movil`, `verificacion`, `email_encriptado`) VALUES
(1, 'admin', 'Yessi', 'yessicac187@gmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/1/689.jpg', NULL, NULL, NULL, NULL, NULL, 1, '7f429a4aea4f0a7baa5d90c94d06d7b3'),
(2, 'admin', 'Sebas', 'sebas@gmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/16/353.jpg', NULL, NULL, NULL, NULL, NULL, 1, '7f429a4aea4f0a7baa5d90c94d06d7b3'),
(3, 'admin', 'Niko', 'niko@gmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/16/353.jpg', NULL, NULL, NULL, NULL, NULL, 1, 'b53cd9a1596e6564dc93e28ebebb707c'),
(4, 'usuario', 'Alexander Parra', 'alexander@gmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/2/559.png', NULL, NULL, NULL, NULL, NULL, 1, 'aaf98bbf03aff90b36e5f1343067d5e5'),
(5, 'usuario', 'Jaime Carrillo', 'jaime@gmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/5/911.jpg', NULL, NULL, NULL, NULL, NULL, 1, 'a6fa2ff49c6efcee56d5fc943ff6126e'),
(6, 'usuario', 'Ana Gonzalez', 'ana@gmail.co', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/5/911.jpg', NULL, NULL, NULL, NULL, NULL, 1, '55084db2f2547c5f8a3879a0b564a9de'),
(7, 'usuario', 'Lorena Perez', 'lorena@hotmail.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/5/911.jpg', NULL, NULL, NULL, NULL, NULL, 1, '55084db2f2547c5f8a3879a0b564a9de'),
(8, 'usuario', 'Marta Alvarez', 'marta@yahoo.com', '$2a$07$asxx54ahjppf45sd87a5auFL5K1.Cmt9ZheoVVuudOi5BCi10qWly', NULL, 'vistas/img/usuarios/16/353.jpg', NULL, NULL, NULL, NULL, NULL, 1, '7f429a4aea4f0a7baa5d90c94d06d7b3');



-- -----------------------------------------------------
-- Table `crm`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  `correo` VARCHAR(30) NULL,
  `celular` VARCHAR(45) NULL,
  `origen` TEXT NULL,
  `fecha` TIMESTAMP(6) NULL,
  `estado` TEXT NULL,
  `pais` TEXT NULL,
  `codigo_pais` TEXT NULL,
  `ciudad` TEXT NULL,
  `direccion` TEXT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `usuarios_id_usuario`),
  INDEX `fk_clientes_usuarios_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_usuarios`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `crm`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `clientes` (`id_cliente`, `nombre`, `correo`, `celular`, `origen`, `fecha`, `estado`, `pais`, `codigo_pais`, `ciudad`, `direccion`, `usuarios_id_usuario`) VALUES
(1, 'Pepito Perez', 'pepitoperez@gmail.com', '3108661309', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(2, 'Fabio Cruz', 'fabiocruz@gmail.com', '3108661309', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(3, 'Laura Lopez', 'lauralopez@gmail.com', '3108661309', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2),
(4, 'Alexander Parra', 'fabiocruz@gmail.com', '3108661309', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);



-- -----------------------------------------------------
-- Table `crm`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`seguimiento` (
  `id_seguimiento` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP(6) NULL,
  `observaciones` TEXT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `clientes_usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_seguimiento`, `clientes_id_cliente`, `clientes_usuarios_id_usuario`),
  INDEX `fk_seguimiento_clientes1_idx` (`clientes_id_cliente` ASC, `clientes_usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_clientes1`
    FOREIGN KEY (`clientes_id_cliente` , `clientes_usuarios_id_usuario`)
    REFERENCES `crm`.`clientes` (`id_cliente` , `usuarios_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  `correo` VARCHAR(30) NULL,
  `celular` VARCHAR(45) NULL,
  `nit` TEXT NULL,
  `logo` TEXT NULL,
  `fecha` TIMESTAMP(6) NULL,
  `pais` TEXT NULL,
  `codigo_pais` TEXT NULL,
  `ciudad` TEXT NULL,
  `direccion` TEXT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
